### ISSUE TITLE
Use of term "blade"

### ISSUE THREAD

**Issue by julieMSFT** [ctesta-oneillmsft/kaito#1]
I believe this terminology should not be used. 

https://github.com/ctesta-oneillmsft/kaito/blob/master/demos/module1/README.md#surveying-the-components-of-azure-synapse-analytics
"The SQL pool is shown below with the Essentials portion of the Overview blade collapsed."
"At the bottom of the Overview blade,"
"Go back to the Synapse Workspace overview blade in the portal,"

may be other insgtances.

**Comment by ctesta-oneillmsft** [comment]
hi @julieMSFT 

Can you suggest what should be used?

**Comment by julieMSFT** [comment]
hi @ctesta-oneillmsft, the cloud sytyle guide says to use pane. I think page works as well.
![image](https://user-images.githubusercontent.com/44736634/98878144-1c357a00-2437-11eb-859d-8724434fb951.png)

**Comment by joelhulen** [comment]
Fixed in the latest round of updates.
