### ISSUE TITLE
Functionality available in Synapse Studio

### ISSUE THREAD

**Issue by julieMSFT** [ctesta-oneillmsft/kaito#2]
I believe this functionality is also available in the Studio, not just the portal.

https://github.com/ctesta-oneillmsft/kaito/blob/master/demos/module1/README.md#surveying-the-components-of-azure-synapse-analytics

Here are some of the common features you'll access through the portal:

At the top of the window, we see controls (1) to pause, scale, restore, set a new restore point, and delete the pool.

**Comment by ctesta-oneillmsft** [comment]
It is, and this is covered later in the module here:

https://github.com/ctesta-oneillmsft/kaito/blob/master/demos/module1/README.md#the-manage-hub

The instructional design decision at this section of the presentation is to deliberately focus on the portal only
