### ISSUE TITLE
CosmosDB Script Error

### ISSUE THREAD

**Issue by Kaijisse** [ctesta-oneillmsft/kaito#24]
USE master
GO

IF DB_ID (N'Profiles') IS NULL
BEGIN
    CREATE DATABASE Profiles;
END
GO

USE Profiles
GO

DROP VIEW IF EXISTS UserProfileHTAP;
GO

CREATE VIEW UserProfileHTAP
AS
SELECT
    *
FROM OPENROWSET(
    'CosmosDB',
    N'account=YOUR_ACCOUNT_NAME;database=CustomerProfile;key=YOUR_ACCOUNT_KEY',
    UserProfileHTAP
)
WITH (
    userId bigint,
    cartId varchar(50),
    preferredProducts varchar(max),
    productReviews varchar(max)
) AS profiles
CROSS APPLY OPENJSON (productReviews)
WITH (
    productId bigint,
    reviewText varchar(1000)
) AS reviews
GO

This script doesn't seem to work. I wonder if it has something to do with this: N'account=asacosmosdb01;database=CustomerProfile;key=gErkZNkMnijcdjLI6eDDH0DJPoM6zZLIgz161WuJrVJD8NDGK9vd5ab7qs2zsHz6shPBh0R3DDJ1k3HjenvUuw==',
Since there are hyphens or high comma's but I'm not so sure?

**Comment by joelhulen** [comment]
This error is because you used the incorrect account name for Cosmos DB. You need to get the account name from the portal. It appears that you used the name of the linked service you added in Synapse.

**Comment by Kaijisse** [comment]
Correct. It works now. No need to take any action and my mistake. My apologies.
