### ISSUE TITLE
Mod 3 Spark Scripts not working

### ISSUE THREAD

**Issue by Kaijisse** [ctesta-oneillmsft/kaito#27]
In whole module 3 none of the scripts attached to the sparkpool set with language pyspark are not working. 
For example:
%%pyspark
df = spark.read.load('abfss://twitterdata@asadatalakekw.dfs.core.windows.net/dbo.TwitterAnalytics.parquet', format='parquet')
display(df.limit(10))

NameError : name 'display' is not defined Traceback (most recent call last): NameError: name 'display' is not defined

Also where instruction says:
1. This generates a notebook with PySpark code to load the data in a Spark dataframe and display 100 rows with the header.
Make sure the Spark pool is attached to the notebook.

Same code error. 
![errorsparkpooldisplay](https://user-images.githubusercontent.com/38757647/110744911-633f4a80-8232-11eb-901e-e75f4320bf0c.png)

**Comment by joelhulen** [comment]
I've updated the environment setup artifacts to exclude the requirements file for the Spark pool. This seems to have cleared the issue that was probably due to a version conflict.
