### ISSUE TITLE
Make status plural

### ISSUE THREAD

**Issue by julieMSFT** [ctesta-oneillmsft/kaito#5]
https://github.com/ctesta-oneillmsft/kaito/blob/master/demos/module1/README.md#the-monitor-hub

I think the word status need to be plural to work with the sentence.

Use the Monitor hub to view pipeline and trigger runs, integration runtime statuses, Apache Spark jobs, SQL requests, and data flow debug activities. If you want to see the status of a job or activity, this is where you want to go.

**Comment by ctesta-oneillmsft** [comment]
Changed the content to:

Use the Monitor hub to view pipeline and trigger runs, view the status of the various integration runtimes that are running, view Apache Spark jobs, SQL requests, and data flow debug activities. If you want to see the status of a job or activity, this is where you want to go.
