### ISSUE TITLE
Define IR

### ISSUE THREAD

**Issue by julieMSFT** [ctesta-oneillmsft/kaito#6]
https://github.com/ctesta-oneillmsft/kaito/blob/master/demos/module1/README.md#the-manage-hub

This section needs IR defined.

Integration runtimes *(IR)* lists the IR for the workspace, which serve as the compute infrastructure for data integration capabilities, like those provided by pipelines. Task: Hover over the integration runtimes to show the monitoring, code, and delete (if applicable) links. Click on a code link to show how you can modify the parameters in JSON format, including the TTL (time to live) setting for the IR

**Comment by ctesta-oneillmsft** [comment]
There is separate content - PowerPoint to support the virtual training days, and Learn content once published. In this situation the definition of these components are there to provide the in depth definitions
