### ISSUE TITLE
Sentence fragment

### ISSUE THREAD

**Issue by julieMSFT** [ctesta-oneillmsft/kaito#7]
https://github.com/ctesta-oneillmsft/kaito/blob/master/demos/module1/README.md#the-modern-data-warehouse-value-proposition

This second sentence is missing a verb.

There is more to a data warehouse than simply storing business data. Data grows at an exponential rate, year over year. **Not just the volume of data, but the variety of data, from structured, to semi-structured, and to a greater degree, unstructured.**

**Comment by ctesta-oneillmsft** [comment]
Changes the content to

There is more to a data warehouse than simply storing business data. Data grows at an exponential rate, year over year. Not just the *volume* of data, but the *variety* of data, from structured, to semi-structured, and to a greater degree, unstructured that **must be managed.**
