### ISSUE TITLE
Synapse pool

### ISSUE THREAD

**Issue by julieMSFT** [ctesta-oneillmsft/kaito#9]
Hi, [in this section](https://github.com/ctesta-oneillmsft/kaito/blob/master/demos/module1/README.md#stage-1-data-ingest-and-preparation) item 7, item iv. is says:

In the top path of the data flow, we select all columns, then load the data into the AggregatedSales_SAPHANANew Synapse pool table (Select the Selectallcolumns activity and the LoadtoAzureSynapse activity).

Which Synapse pool are we talking about? is this a spark pool or a sql pool?

same question for item vii.

**Comment by joelhulen** [comment]
Fixed in the latest round of updates.
